name: bloom_flutter
description: Astrology-based dating app
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  # State management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.1
  
  # Backend
  supabase_flutter: ^2.0.2
  
  # Utilities
  equatable: ^2.0.5
  intl: ^0.19.0
  uuid: ^4.2.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  
  # Location
  geolocator: ^10.1.0
  
  # Image
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  ssl_pinning_plugin: ^2.0.0
  flutter_jailbreak_detection: ^1.10.0
  
  # Offline support
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Analytics & Monitoring
  sentry_flutter: ^7.16.0
  posthog_flutter: ^3.3.0
  
  # Accessibility
  flutter_tts: ^3.8.5
  
  # JSON
  json_annotation: ^4.8.1

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.3
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env.development
    - .env.staging
    - .env.production

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: bloom-op
